name: Build and Commit

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - run: npm ci

      - run: npm run build

      - name: Update demo files
        run: |
          cp dist/gantt-chartmeleon.umd.js demo/gantt-chartmeleon.js
          cp dist/gantt-chartmeleon.css demo/gantt-chartmeleon.css
          
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add demo/
          
          if ! git diff --staged --quiet; then
            git commit -m "Update demo build [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
